Adding DevContainer config + Tweak the config files
Philess/gh-copilot-demo pull request #2
Opened 2023-06-20 16:58 UTC by Justrebl

Fixing the config files to start the apps with the commands in build and run.md 

Adding a fully functionnal Devcontainer config.

2023-06-21 08:22 UTC, Philess requested changes
Ca m'a l'air OK (je n'ai pas testé par manque de temps mais je te fais confiance et je checkerai ASAP)
Il y a juste les fichier validators qui ne devaient pas être poussé dans la branche et à clean :)

2023-06-21 08:22 UTC, Philess commented on album-viewer/tests/validator.tests.ts
@Justrebl  Fichier à dégager car créé pendant l'exercice

2023-06-30 20:31 UTC, Justrebl commented
Fixé, les configs sont à nouveau OK

2023-06-30 20:34 UTC, Justrebl reviewed
Reviewed

2023-06-30 20:43 UTC, Justrebl reviewed
Done

2023-07-03 07:39 UTC, Philess approved these changes

2023-07-03 07:39 UTC, merged